
const stateData = {
  INAN: { name:"Andaman & Nicobar",craft:"Shell & Coconut Shell Craft",desc:"Intricate handicrafts made from sea shells and coconut shells—bowls, lamps, jewelry, and figurines uniquely shaped by island artisans.",about:"The islands are famous for exquisite shell craft using naturally available sea shells and coconut shells. Artisans create stunning decorative items, lamps, jewelry, and figurines. The craft blends tribal and maritime heritage.",history:"Evolved over centuries by indigenous islanders who used shells as currency, ornament, and spiritual objects.",techniques:["Shell carving","Coconut inlay","Natural polishing","Lacquering"],materials:"Sea shells, coconut shells, bamboo, natural dyes, organic resins",products:["Shell jewelry","Decorative lamps","Wall hangings","Showpieces"],recognition:"A registered cottage industry under A&N Administration. Popular as souvenir items.",tags:["Shells","Coastal","Tribal","Island Craft","Eco Souvenirs"]},
  INAP: { name:"Andhra Pradesh",craft:"Kondapalli Toys & Kalamkari",desc:"Brightly painted wooden Kondapalli toys depicting folk scenes, and hand-painted Kalamkari textiles with mythological narratives in natural dyes.",about:"Andhra Pradesh is celebrated for two iconic crafts: Kondapalli wooden toys—intricately carved and lacquered depictions of deities, animals, and rural life—and Kalamkari, a pen-and-block painting tradition on cotton fabric using natural dyes to portray epics and mythology.",history:"Kondapalli toys have a 400-year heritage from the village of the same name. Kalamkari (Srikalahasti style) dates to ancient temple traditions of creating cloth narratives for worship.",techniques:["Wood carving","Lac polishing","Hand painting","Natural dyeing","Kalam (pen) drawing","Block printing"],materials:"Tella poniki wood, lac, natural dyes (indigo, pomegranate), cotton fabric, bamboo pens",products:["Kondapalli dolls","Kalamkari sarees","Wall panels","Temple hangings"],recognition:"Both Kondapalli Toys and Kalamkari hold GI (Geographical Indication) tags from India.",tags:["GI Tagged","Wood Craft","Textile","Natural Dyes","Mythology","Folk Art"]},
  INAR: { name:"Arunachal Pradesh",craft:"Cane & Bamboo Craft",desc:"Skilled tribal artisans weave cane and bamboo into baskets, hats, household items, and musical instruments with remarkable precision.",about:"Arunachal Pradesh's dense forests yield abundant cane and bamboo, which tribal communities have woven for millennia into functional and decorative objects—ranging from storage baskets and hats to furniture, musical instruments, and ritual objects.",history:"Indigenous tribes like Adi, Nyishi, and Monpa have practiced cane-bamboo weaving for over 2,000 years as essential daily craft.",techniques:["Twill weaving","Coil weaving","Plaiting","Splicing","Natural dyeing"],materials:"Cane, bamboo, rattan, plant dyes, natural lacquer",products:["Jakoi fish traps","Tribal hats","Bamboo mugs","Woven baskets","Furniture"],recognition:"Recognized under India's Development Commissioner for Handicrafts. Essential to tribal livelihoods.",tags:["Tribal","Bamboo","Eco-friendly","North East India","Weaving"]},
  INAS: { name:"Assam",craft:"Assam Silk Weaving (Muga & Pat)",desc:"Shimmering Muga silk—the world's only naturally golden silk—woven into mekhela chadors and sarees with intricate motifs unique to Assam.",about:"Assam produces three renowned silks: golden Muga, creamy Pat, and Eri. Muga silk, spun from silkworms that feed on som and sualu trees, has a natural golden lustre that deepens with age.",history:"Silk weaving in Assam dates to antiquity; Muga silk was patronized by Ahom kings and mentioned in ancient texts.",techniques:["Handloom weaving","Natural rearing","Jamdani motif","Temple border design"],materials:"Muga silk yarn, Pat silk, Eri silk, natural and botanical dyes",products:["Mekhela Chador","Muga sarees","Stoles","Gamosa towels"],recognition:"Muga silk has a GI tag. Assam Silk is protected by the Silk Mark Organization of India.",tags:["GI Tagged","Silk","Golden Silk","Handloom","North East","Luxury Textile"]},
  INBR: { name:"Bihar",craft:"Madhubani Painting",desc:"Vivid two-dimensional paintings by Mithila women depicting deities, nature, and social themes—bold outlines filled with rich natural hues.",about:"Madhubani (Mithila) painting is one of India's most iconic folk art traditions. Created by women of the Mithila region, these paintings use natural pigments to depict Hindu mythology, nature, and auspicious occasions.",history:"Originated over 2,500 years ago. Paintings were traditionally created on walls and floors for weddings and festivals. Revived on paper and canvas in the 1960s.",techniques:["Double outline","Nib drawing","Space filling","Natural pigment preparation","Finger/twig painting"],materials:"Cotton fabric, handmade paper, neem twigs, natural pigments from turmeric, indigo, sandalwood",products:["Framed paintings","Painted sarees","Gift cards","Wall murals","Notebooks"],recognition:"GI tag awarded in 2007. UNESCO recognized Madhubani as an important intangible cultural heritage.",tags:["GI Tagged","Folk Painting","Mithila","Women Artisans","UNESCO","Natural Pigments"]},
  INCH: { name:"Chandigarh",craft:"Phulkari Embroidery",desc:"Vibrant floral embroidery from Punjab tradition—silky thread on hand-spun cotton creating geometric flowers for dupattas and shawls.",about:"Phulkari ('flower craft') embroidery uses colorful silk floss on hand-spun cotton to create dazzling floral and geometric patterns. It adorns dupattas, shawls, and garments for weddings and celebrations.",history:"Ancient Punjabi women's tradition dating back centuries, associated with the trousseau and gifted at weddings.",techniques:["Darning stitch","Reverse running","Counted thread work","Mirror work","Surface embroidery"],materials:"Khaddar (hand-spun cotton), silk floss (pat), natural and synthetic dyes",products:["Phulkari dupatta","Bagh shawl","Embroidered suits","Wall hangings"],recognition:"GI tag for Phulkari. Associated with both Chandigarh and Punjab traditions.",tags:["GI Tagged","Embroidery","Punjab Heritage","Floral","Wedding Craft"]},
  INCT: { name:"Chhattisgarh",craft:"Dhokra Metal Casting",desc:"Ancient lost-wax bell metal casting producing tribal figurines, animals, and jewelry—one of India's oldest non-ferrous metal craft traditions.",about:"Dhokra craft uses the lost-wax (cire perdue) casting process to create exquisite bell metal objects. Tribal artisans fashion figures of elephants, horses, goddesses, and decorative items.",history:"Over 4,000 years old—among the world's oldest known metal casting techniques. The dancing girl of Mohenjo-daro is believed to be a Dhokra artifact.",techniques:["Lost-wax casting","Wax thread modeling","Clay molding","Charcoal firing","Metal pouring"],materials:"Brass (copper + zinc + tin), beeswax, clay, charcoal",products:["Tribal figurines","Jewelry","Lamps","Decorative animals","Wall plaques"],recognition:"Recognized under India's Development Commissioner for Handicrafts. Strong tribal identity.",tags:["Tribal","Metal Casting","Ancient Craft","Lost-Wax","Figurines","4000 Years Old"]},
  INDH: { name:"Dadra & Nagar Haveli",craft:"Warli Tribal Painting",desc:"Simple white geometric folk paintings on mud walls by the Warli tribe—circles, triangles, and squares telling stories of daily life.",about:"Warli paintings are the visual language of the Warli tribe—white rice paste on an ochre mud base, depicting village life, nature, festivals, and rituals through elementary geometric shapes.",history:"Practiced for over 2,500 years. Formally documented and revived in the 1970s by Jivya Soma Mashe.",techniques:["Rice paste painting","Geometric composition","Chowk (ritual square)","Tarpa (flute) dance motif"],materials:"Rice powder, water, gum, mud, bamboo sticks, red ochre earth",products:["Painted fabric","Wall murals","Paper art","Printed textiles"],recognition:"Internationally recognized tribal art. Jivya Soma Mashe received Padma Shri in 2011.",tags:["Tribal","Folk Painting","Geometric","White on Brown","Maharashtra-UT boundary"]},
  INDL: { name:"Delhi",craft:"Zardozi Embroidery",desc:"Opulent gold and silver thread embroidery using real metallic threads, sequins, and semi-precious stones—the crown jewel of Mughal textile arts.",about:"Zardozi (Persian: 'gold sewing') is heavy and luxurious embroidery using real gold and silver wires, combined with silk thread, pearls, and precious stones. It adorns royal garments, bridal wear, and ceremonial textiles.",history:"Introduced to India by the Mughals, Zardozi reached its zenith under Emperor Akbar. Revived post-Independence with craft patronage.",techniques:["Metal thread couching","Aari needle work","Sequin attachment","Goldwork shading","Stone setting"],materials:"Real gold/silver wire, silk fabric, sequins, beads, semi-precious stones",products:["Bridal lehengas","Sherwanis","Sarees","Caps","Decorative cushions"],recognition:"GI tag for Delhi Zardozi. Craft patronized by National Institute of Fashion Technology (NIFT).",tags:["GI Tagged","Mughal Heritage","Luxury","Bridal","Goldwork","Zardozi"]},
  INGA: { name:"Goa",craft:"Azulejo Tile Work & Crochet",desc:"Portuguese-influenced hand-painted blue and white ceramic tiles adorning historic mansions, alongside fine crochet lace from coastal villages.",about:"Goa's craft heritage reflects its Portuguese colonial past. Azulejo tiles—hand-painted ceramic tiles with intricate blue and white motifs—decorate historic churches, mansions, and public spaces. Crochet lacemaking is practiced in coastal communities.",history:"Tile tradition brought by Portuguese colonizers in the 15th century. Crochet introduced by Catholic missionaries.",techniques:["Ceramic painting","Hand-painted glaze firing","Crochet lacemaking","Transfer printing"],materials:"White clay, ceramic glazes, cobalt oxide, cotton thread, linen",products:["Decorative tiles","Wall panels","Crochet tablecloths","Lace blouses","Cushion covers"],recognition:"Recognized craft under Goa Handicrafts, Rural and Small Scale Industries Development Corporation.",tags:["Portuguese Heritage","Coastal","Ceramics","Crochet","Colonial Art","Tiles"]},
  INGJ: { name:"Gujarat",craft:"Bandhani & Patola Weaving",desc:"Intricate tie-dye Bandhani textiles and prized double-ikat Patola silks—two of India's most technically demanding textile traditions.",about:"Gujarat offers a treasure of textile crafts. Bandhani involves tying thousands of tiny knots on fabric before dyeing. Patola silks are double-ikat woven—among the most complex weaves in the world.",history:"Patola weaving practiced in Patan for over 700 years, exclusively by the Salvi community. Bandhani integral to Gujarati weddings since ancient times.",techniques:["Tie-dyeing","Resist dyeing","Double-ikat weaving","Bandhani knot tying","Block printing"],materials:"Silk, cotton, natural dyes, mordants, resist wax",products:["Bandhani sarees","Patola silks","Odhni dupattas","Chaniya choli","Block printed fabrics"],recognition:"Patan Patola has a GI tag. Both crafts are among India's most coveted textiles.",tags:["GI Tagged","Double Ikat","Tie-Dye","Luxury Textile","Silk","Wedding Wear"]},
  INHP: { name:"Himachal Pradesh",craft:"Kullu Shawls & Chamba Rumal",desc:"Vibrant handwoven Kullu shawls with bold geometric borders, and delicate Chamba Rumal embroideries with scenes from epics on fine cloth.",about:"Himachal Pradesh offers two signature textile crafts. Kullu shawls are thick handwoven wool shawls with striking multicolored geometric patterns. Chamba Rumal is fine embroidery on muslin where both sides look identical, depicting scenes from Mahabharata and Ramayana.",history:"Kullu shawls woven for centuries by mountain communities. Chamba Rumal reached its peak under patronage of Chamba kings (17th–19th century).",techniques:["Handloom weaving","Double-sided embroidery","Wool dyeing","Natural color mordanting"],materials:"Merino wool, angora, pashmina, silk threads, muslin cloth",products:["Kullu shawls","Chamba Rumal squares","Wool stoles","Embroidered cushions"],recognition:"Kullu Shawl and Chamba Rumal both hold GI tags.",tags:["GI Tagged","Himalayan","Wool Craft","Embroidery","Mountain Weaving","Shawls"]},
  INHR: { name:"Haryana",craft:"Phulkari & Pottery",desc:"Intricate floral thread embroidery on coarse cotton cloth, alongside terracotta pottery with painted folk motifs from Haryana's craft villages.",about:"Haryana shares the Phulkari tradition with Punjab—vibrant floral silk-thread embroidery on coarse cotton for festive and bridal use. The state also has a living tradition of blue pottery and hand-painted terracotta.",history:"Phulkari rooted in ancient rural women's crafts; terracotta traditions go back to Harappan civilization in this region.",techniques:["Darning stitch embroidery","Terracotta molding","Slip painting","Kiln firing","Lacquerwork"],materials:"Khaddar cotton, silk threads, terracotta clay, natural mineral pigments",products:["Phulkari dupattas","Pottery items","Water pots","Decorative plates","Embroidered jackets"],recognition:"Phulkari GI tag shared with Punjab. Haryana Handloom & Handicrafts Corporation supports artisans.",tags:["Embroidery","Pottery","Folk Craft","Phulkari","Terracotta","Heritage"]},
  INJH: { name:"Jharkhand",craft:"Dokra & Sohrai Painting",desc:"Tribal Dokra bell-metal casting alongside Sohrai wall paintings—geometric and animal motifs painted by tribal women on harvest festival walls.",about:"Jharkhand's tribal artistry shines in two iconic crafts. Dokra is the ancient lost-wax metal casting. Sohrai painting is a ritual art where tribal women decorate their homes at harvest time with natural earth pigments.",history:"Both crafts trace to prehistoric tribal cultures of the Jharkhand plateau. Sohrai specifically tied to the harvest festival of the same name.",techniques:["Lost-wax casting","Earth pigment preparation","Finger painting","Animal motif drawing","Natural color extraction"],materials:"Brass alloy, beeswax, clay, red/white/black earth pigments, chalk",products:["Tribal figurines","Sohrai prints","Wall panels","Jewelry","Paintings on paper"],recognition:"Both crafts supported under Jharkhand Silk Textile and Handicraft Development Corporation.",tags:["Tribal","Metal Casting","Wall Painting","Harvest Festival","Sohrai","Dokra"]},
  INJK: { name:"Jammu & Kashmir",craft:"Kashmir Pashmina & Kani Weaving",desc:"Supremely fine Pashmina shawls from Changthangi goat fleece, and kani-woven shawls with incredible floral and paisley designs using wooden bobbins.",about:"Kashmir's pashmina shawls are the world's finest, woven from the soft undercoat of the Changthangi goat raised at 14,000 feet. Kani weaving uses wooden bobbins (twill tapestry) to create incredibly complex floral and paisley designs.",history:"Pashmina weaving flourished under Sultan Zain-ul-Abidin in the 15th century. The famous 'ring shawl' that passes through a finger ring represents the pinnacle of the craft.",techniques:["Kani (bobbin) weaving","Twill tapestry","Sozni embroidery","Natural dyeing","Hand spinning"],materials:"Pashmina (Changthangi goat fleece), silk warp, natural saffron/walnut/indigo dyes",products:["Pashmina shawls","Kani shawls","Kashmir carpets","Sozni stoles"],recognition:"Kashmir Pashmina holds a GI tag. Among India's highest-valued craft exports.",tags:["GI Tagged","Luxury Textile","Pashmina","Kani Weaving","Himalayan","Shawls"]},
  INKA: { name:"Karnataka",craft:"Mysore Silk & Bidriware",desc:"Lustrous Mysore silk sarees with real zari, and Bidriware—dark alloy inlaid with silver in stunning geometric and floral patterns from Bidar.",about:"Karnataka has two iconic crafts: Mysore Silk sarees woven with pure mulberry silk and real gold-zari borders. Bidriware is a metal craft from Bidar—a zinc-copper alloy turned black, then inlaid with pure silver.",history:"Mysore Silk promoted by Hyder Ali and Tipu Sultan. Bidriware originated in the 14th century Bahmani Sultanate, named after Bidar city.",techniques:["Silk weaving","Real zari inlay","Bidri alloy casting","Silver inlay engraving","Ammonium chloride blackening"],materials:"Mulberry silk, gold zari, zinc-copper alloy, pure silver wire, ammonium chloride",products:["Mysore silk sarees","Bidri vases","Bidri jewelry","Bidri hookah bases","Silk stoles"],recognition:"Mysore Silk and Bidriware both hold GI tags.",tags:["GI Tagged","Silk","Metal Craft","Silver Inlay","Luxury","Mysore Heritage","Bidar"]},
  INKL: { name:"Kerala",craft:"Kasavu Sarees & Kathakali Masks",desc:"Elegant off-white Kasavu sarees with golden borders worn at Onam, and richly painted Kathakali masks representing the classical dance-drama tradition.",about:"Kerala's Kasavu saree is handwoven with cream cotton body and wide golden zari border—the essential attire for Onam and temple festivals. Kathakali costume masks are crafted from papier-mâché and natural materials, painted in vivid iconography.",history:"Kasavu weaving tradition over 500 years old, centered in Balaramapuram. Kathakali masks evolved with the dance form in the 17th century.",techniques:["Handloom weaving","Gold zari border work","Papier-mâché molding","Natural paint application","Coir weaving"],materials:"Cotton yarn, gold zari, paper pulp, natural pigments, coir fiber",products:["Kasavu sarees","Kathakali masks","Coir products","Kerala murals","Lacquerware"],recognition:"Balaramapuram Saree and Kasavu hold GI tags.",tags:["GI Tagged","Handloom","Golden Border","Classical Dance","Coir","Temple Textile","Onam"]},
  INLA: { name:"Ladakh",craft:"Thangka Painting & Pashmina",desc:"Sacred Buddhist Thangka scroll paintings in mineral pigments on cotton, and handwoven Pashmina from Changthangi goats of the Chang-La plateau.",about:"Ladakh's crafts are deeply connected to Buddhist culture. Thangka paintings are intricate scrolls depicting Buddhist deities, mandalas, and cosmological maps—painted with mineral pigments and gold on cotton or silk.",history:"Thangka tradition arrived with Buddhism in the 7th century. Pashmina from this plateau has been traded since ancient times along the Silk Road.",techniques:["Mineral pigment preparation","Gold outlining","Thangka scroll mounting","Pashmina spinning","Handloom weaving"],materials:"Cotton canvas, silk, mineral pigments, 24K gold, Pashmina fleece",products:["Thangka scrolls","Pashmina shawls","Wooden prayer wheels","Metalwork","Yak wool crafts"],recognition:"Ladakh Pashmina is a protected GI product. Thangka painting recognized as living intangible heritage.",tags:["Buddhist Art","Thangka","Pashmina","Sacred Craft","Silk Road","Himalayan","GI Tagged"]},
  INLD: { name:"Lakshadweep",craft:"Coconut Shell & Coir Craft",desc:"Delicate handicrafts fashioned from coconut shells—bowls, lamps, and jewelry—alongside coir rope weaving, shaped by island life.",about:"With abundant coconut palms, Lakshadweep artisans have perfected the art of crafting from every part of the coconut. Shells become polished bowls, lamps, and jewelry; coir fiber is twisted into ropes and woven into mats.",history:"Island craft tradition developed over centuries by islanders making use of available natural resources.",techniques:["Shell polishing","Coir rope spinning","Weaving","Natural lacquering","Carving"],materials:"Coconut shells, coir fiber, natural oils, natural dyes",products:["Shell bowls","Coir mats","Coconut oil lamps","Jewelry","Decorative trays"],recognition:"Cottage industry supported by the Lakshadweep Administration.",tags:["Island Craft","Eco-Friendly","Coconut","Coir","Sustainable","Ocean Heritage"]},
  INMH: { name:"Maharashtra",craft:"Paithani Silk Weaving",desc:"Luxurious handwoven silk sarees with oblique twill interlocking creating shimmering peacock and lotus motifs—an art from Paithan, Maharashtra.",about:"Paithani sarees are among India's most prized weaves. Using an oblique interlocking technique (tapestry weaving), weavers create images of peacocks, lotuses, and vines in pure silk and real zari. Each saree can take months to years.",history:"Originating in Paithan (ancient Pratishthana) on the Godavari, Paithani sarees were patronized by Satavahana kings and later by the Peshwas.",techniques:["Tapestry weave","Oblique interlocking","Real zari inlay","Peacock motif design","Hand shuttle weaving"],materials:"Pure mulberry silk, real gold zari, silver zari, natural and synthetic dyes",products:["Paithani sarees","Paithani dupattas","Stoles","Silk fabric yardage"],recognition:"Paithani holds a GI tag. Among the most expensive handwoven sarees in India.",tags:["GI Tagged","Silk","Luxury Weave","Peacock Motif","Heirloom","Peshwa Heritage"]},
  INML: { name:"Meghalaya",craft:"Cane & Bamboo Weaving",desc:"Intricate tribal basketry and furniture woven from cane and bamboo by Khasi, Garo, and Jaintia artisans—functional beauty born from the forest.",about:"Meghalaya's tribal communities are master weavers of cane and bamboo. They craft baskets, furniture, fish traps, hats, and storage containers using complex weave patterns unique to each tribe.",history:"Weaving traditions predate recorded history, deeply embedded in tribal identity and daily life in the bamboo-rich hills.",techniques:["Twill weave","Plaiting","Diagonal weave","Natural dyeing","Splicing and joinery"],materials:"Cane, bamboo, rattan, grass, natural plant dyes",products:["Bamboo baskets","Tribal hats","Furniture","Food steaming vessels","Decorative trays"],recognition:"Supported under North East Handicrafts and Handlooms Development Corporation (NEHHDC).",tags:["Tribal","Bamboo","North East India","Eco Craft","Forest Heritage","Functional Art"]},
  INMN: { name:"Manipur",craft:"Moirang Phee Weaving",desc:"Handwoven Manipuri textiles featuring sacred geometric patterns from the Moirang tradition, alongside Kauna mat weaving and Longpi black pottery.",about:"Manipur's textile heritage centers on Moirang Phee—sacred handwoven fabric with intricate geometric and lotus patterns. The state also produces unique Longpi black pottery (hand-beaten without a wheel).",history:"Moirang Phee connected to the ancient Moirang kingdom and pre-Hindu Meitei traditions. Longpi pottery practiced by Tangkhul Naga tribe for centuries.",techniques:["Handloom weaving","Pattern designing","Hand-beating pottery","Kauna mat plaiting","Natural dyeing"],materials:"Mulberry silk, cotton, aquatic sedge (kauna), serpentine stone, clay",products:["Moirang Phee fabric","Longpi cookware","Kauna mats","Phanek (skirt)","Woven bags"],recognition:"Manipuri handloom has GI protection. Longpi pottery is a protected craft of Manipur.",tags:["GI Tagged","North East","Handloom","Black Pottery","Sacred Textile","Tribal"]},
  INMP: { name:"Madhya Pradesh",craft:"Chanderi Sarees & Gond Painting",desc:"Diaphanous Chanderi silk-cotton sarees with sheer golden borders, and vibrant Gond tribal paintings depicting nature and spirituality.",about:"Madhya Pradesh is home to the ethereal Chanderi saree—a translucent blend of silk and cotton woven with golden buttas and borders—and Gond painting, featuring intricate dot-and-line animals and cosmological scenes.",history:"Chanderi weaving mentioned in Mughal-era records; patronized by Bundela kings. Gond painting brought to mainstream attention by Jangarh Singh Shyam in the 1980s.",techniques:["Chanderi weave (silk-cotton)","Gold zari work","Gond dot-line technique","Natural pigment use","Pattern drafting"],materials:"Silk, cotton, gold and silver zari, natural and acrylic paints, paper, canvas",products:["Chanderi sarees","Gond paintings","Maheshwari sarees","Kosa silk fabric","Painted stationery"],recognition:"Chanderi Fabric and Maheshwari Saree both hold GI tags. Gond art internationally exhibited.",tags:["GI Tagged","Saree","Tribal Art","Chanderi","Gond","Folk Painting","Diaphanous Weave"]},
  INMZ: { name:"Mizoram",craft:"Puan Weaving",desc:"Vibrant handwoven cotton Puan fabrics with intricate geometric patterns—the cultural textile identity of the Mizo people used in every ceremony.",about:"The Puan is the quintessential Mizo textile—a handwoven cotton fabric characterized by bold geometric and checkered patterns. Every Mizo celebration requires specific Puan designs that denote social status and occasion.",history:"Puan weaving is an ancient tradition passed down through generations of Mizo women. Each pattern carries social and cultural meaning.",techniques:["Backstrap loom weaving","Cotton spinning","Pattern counting","Natural dyeing","Geometric design drafting"],materials:"Cotton yarn, natural dyes (red from plants, black from indigo), synthetic bright dyes",products:["Puan cloth","Ceremonial shawls","Traditional costumes","Decorative wall hangings"],recognition:"Recognized under NEHHDC and Ministry of Textiles. Integral to Mizo cultural identity.",tags:["North East India","Tribal Textile","Geometric","Cotton Weaving","Cultural Identity","Handloom"]},
  INNL: { name:"Nagaland",craft:"Naga Tribal Shawl Weaving",desc:"Bold handwoven shawls with geometric warrior motifs unique to each Naga tribe—worn as badges of identity, valor, and social rank.",about:"Each of Nagaland's 16 major tribes has its own distinctive shawl pattern serving as a visual language of identity, achievement, and status. Woven on backstrap looms with bold geometric warrior motifs.",history:"Shawl weaving is inseparable from Naga tribal identity. Warrior shawls were traditionally earned by headhunters, with each pattern awarded for specific deeds.",techniques:["Backstrap loom weaving","Cotton dyeing","Geometric drafting","Warrior motif tradition","Weft pattern weaving"],materials:"Cotton, wool, dog hair (traditional), natural red and black dyes",products:["Warrior shawls","Tribal bags","Ceremonial costumes","Decorative wall textiles"],recognition:"Naga shawls recognized under NEHHDC. Hornbill Festival celebrates shawl-weaving traditions annually.",tags:["Tribal","Warrior Shawl","North East","Identity Textile","16 Tribes","Geometric"]},
  INOR: { name:"Odisha",craft:"Pattachitra & Ikat Weaving",desc:"Sacred scroll paintings with mythological themes from Puri, and double-ikat Sambalpuri sarees with tie-resist patterns from the Mahanadi belt.",about:"Odisha shines with two extraordinary crafts. Pattachitra are traditional cloth paintings created by Chitrakara artists depicting stories of Jagannath and Krishna. Sambalpuri sarees use double-ikat weaving to create nature-inspired patterns.",history:"Pattachitra tradition is over 1,000 years old, tied to the Rath Yatra of Puri. Sambalpuri weaving flourished under patronage of Sambalpur's feudal lords.",techniques:["Cloth preparation with tamarind paste","Mineral paint application","Double-ikat resist dyeing","Handloom weaving","Lacquer finishing"],materials:"Fine cotton cloth, natural pigments, tamarind paste, silk yarn, natural and synthetic dyes",products:["Pattachitra paintings","Sambalpuri sarees","Kotpad fabrics","Palm leaf engravings","Appliqué work"],recognition:"Pattachitra, Sambalpuri Saree, and Kotpad Fabric all hold GI tags.",tags:["GI Tagged","Sacred Painting","Double Ikat","Jagannath","Silk Weaving","Temple Art","Sambalpuri"]},
  INPB: { name:"Punjab",craft:"Phulkari Embroidery",desc:"Dazzling floral embroidery on coarse hand-spun cotton using silk floss—a quintessentially Punjabi craft for weddings and festivals.",about:"Phulkari, meaning 'flower work', is Punjab's most beloved embroidery tradition. Women stitch geometric floral patterns using silk floss on khaddar fabric, working from the reverse side.",history:"An ancient tradition referenced in Punjabi folk songs. Mothers created Phulkari for daughters' trousseaus. Revived as a commercial craft post-Partition.",techniques:["Darning stitch","Back-stitch variations","Reverse-side working","Silk thread shading","Geometric counting"],materials:"Khaddar (hand-spun cotton), silk floss, sometimes with mirror work additions",products:["Phulkari dupatta","Bagh shawl","Embroidered suits","Cushion covers","Wall art"],recognition:"Punjab Phulkari holds a GI tag. One of India's most recognized textile heritage crafts.",tags:["GI Tagged","Embroidery","Floral","Silk Thread","Bridal Craft","Folk Textile","Wedding Art"]},
  INPY: { name:"Puducherry",craft:"Handmade Paper & Auroville Crafts",desc:"Eco-friendly handmade paper from cotton rag and banana fiber, alongside Auroville's internationally acclaimed sustainable craft traditions.",about:"Puducherry is known for environmentally conscious craft practices. The Auroville Handmade Paper unit produces fine art paper from recycled cotton rags and natural fibers.",history:"French colonial influence shaped local craft aesthetics. Auroville, founded in 1968, became a center for sustainable craftsmanship from global traditions.",techniques:["Rag paper beating","Screen forming","Natural dyeing","Woodturning","Leather molding"],materials:"Cotton rags, banana fiber, recycled material, wood, natural dyes, tanned leather",products:["Handmade paper","Art journals","Wooden objects","Leather goods","Natural incense"],recognition:"Auroville crafts internationally recognized. Puducherry's handmade paper exported globally.",tags:["Eco Craft","Sustainable","Handmade Paper","Auroville","French Heritage","Conscious Design"]},
  INRJ: { name:"Rajasthan",craft:"Blue Pottery & Bandhej",desc:"Turquoise-glazed Blue Pottery of Jaipur with Persian floral motifs, and vibrant Bandhej tie-dye textiles from royal Jodhpur workshops.",about:"Rajasthan is India's craft powerhouse. Jaipur Blue Pottery is unique—made from quartz powder, glass, Multani mitti, and borax. Bandhej (Rajasthani tie-dye) creates fine dot patterns by tying tiny bunches of cloth before dyeing.",history:"Blue pottery introduced to Jaipur by Maharaja Sawai Ram Singh II in the 19th century. Bandhej has ancient Rajput royal connections.",techniques:["Quartz-body preparation","Low-fire glaze firing","Persian motif painting","Bandhej tying (tiny knots)","Multi-color dyeing"],materials:"Quartz powder, Fuller's earth, borax, glass powder, oxide glazes, cotton, silk",products:["Blue pottery tiles","Vases","Bandhej sarees","Odhni dupattas","Ceramic plates"],recognition:"Jaipur Blue Pottery has a GI tag. Rajasthan leads India in handicraft exports.",tags:["GI Tagged","Blue Pottery","Tie-Dye","Royal Heritage","Jaipur","Rajput Art","Export Leader"]},
  INSK: { name:"Sikkim",craft:"Thangka Painting & Carpet Weaving",desc:"Buddhist Thangka scroll paintings in gold and mineral pigments, and handwoven Tibetan-style woolen carpets with sacred lotus and dragon motifs.",about:"Sikkim's craft heritage is rooted in Tibetan Buddhism. Thangka paintings are sacred scrolls on cloth depicting Buddhist deities and cosmological mandalas. Handwoven carpets feature Tibetan-influenced dragon and lotus motifs.",history:"Buddhist craft tradition brought with Tibetan immigrants from the 17th century. Chogyal (king) patronized Thangka painters as royal court artists.",techniques:["Thangka sketch drafting","Mineral pigment preparation","Gold application","Carpet knotting","Wool dyeing"],materials:"Cotton canvas, silk, mineral pigments, gold leaf, wool, natural dyes",products:["Thangka scrolls","Wool carpets","Wooden prayer items","Jewelry","Woven bags"],recognition:"Sikkimese crafts promoted by Sikkim Handicraft & Handloom Department.",tags:["Buddhist Art","Thangka","Tibetan Heritage","Sacred Craft","Himalayan","Carpet Weaving"]},
  INTG: { name:"Telangana",craft:"Bidriware & Nirmal Paintings",desc:"Dark alloy inlaid with silver in intricate patterns from Bidar, and Nirmal paintings—lacquered wood panels with vibrant mythological imagery.",about:"Telangana shares the Bidriware tradition (zinc-copper alloy with silver inlay) from Bidar region, and produces Nirmal paintings—flat wooden panels lacquered in brilliant colors depicting epics and mythology.",history:"Bidriware originated under Bahmani Sultanate influence. Nirmal paintings developed under Mughal-era patronage in the Deccan.",techniques:["Bidri casting and silver inlay","Lacquer application","Flat figure painting","Burnishing","Natural color preparation"],materials:"Zinc-copper alloy, pure silver wire, wood, lacquer, natural and mineral pigments",products:["Bidri vases","Nirmal paintings","Lacquered boxes","Decorative panels","Silver inlay jewelry"],recognition:"Bidriware and Nirmal Paintings both hold GI tags.",tags:["GI Tagged","Metal Craft","Lacquer Art","Silver Inlay","Mythology Art","Deccan Heritage"]},
  INTN: { name:"Tamil Nadu",craft:"Kanchipuram Silk & Bronze Casting",desc:"Legendary Kanjivaram silks with contrasting zari borders, and Chola-style bronze casting of Nataraja and deities—icons of India's artistic heritage.",about:"Tamil Nadu's Kanchipuram silk sarees are woven with the thickest, most durable mulberry silk, featuring contrasting colors joined by the traditional kulgai technique and real gold zari. The state also carries the Chola bronze-casting tradition.",history:"Kanjivaram weaving tradition over 1,400 years old. Chola bronzes of the 9th–13th centuries are considered the apex of Indian sculpture.",techniques:["Three-shuttle weaving (korvai)","Real zari work","Lost-wax bronze casting","Patina finishing","Gold border integration"],materials:"Mulberry silk, real gold and silver zari, bronze alloy, beeswax, clay",products:["Kanjivaram sarees","Nataraja bronzes","Temple jewelry","Tanjore paintings","Brass lamps"],recognition:"Kanchipuram Silk Saree holds a GI tag. Chola bronzes listed in UNESCO heritage discussions.",tags:["GI Tagged","Silk","Bronze Casting","Nataraja","Temple Art","Chola Heritage","Luxury Saree"]},
  INTR: { name:"Tripura",craft:"Tribal Weaving & Bamboo Craft",desc:"19 tribal communities weaving distinctive fabric with Rignai and Risa designs, alongside bamboo and cane basketry unique to Northeast forests.",about:"Tripura's 19 tribal communities each have their own weaving tradition. The Rignai and Risa of the Tripuri people feature bold geometric motifs woven on traditional looms. The state is also home to sophisticated bamboo and cane basketry.",history:"Ancient tribal weaving traditions that predate the Tripura royal dynasty. The Maharajas promoted craft centers that blended tribal and Mughal influences.",techniques:["Backstrap loom weaving","Cotton dyeing","Geometric pattern counting","Bamboo splicing","Coil basketry"],materials:"Cotton, silk, bamboo, cane, natural plant dyes",products:["Rignai fabric","Risa shawl","Cane furniture","Bamboo baskets","Woven purses"],recognition:"Supported under NEHHDC. Tripura Tribal Weaving recognized under national craft documentation.",tags:["Tribal","North East","Weaving","Bamboo","19 Communities","Forest Craft","Rignai"]},
  INUP: { name:"Uttar Pradesh",craft:"Chikankari Embroidery & Varanasi Silk",desc:"Delicate white-on-white Chikankari shadow embroidery from Lucknow, and opulent Banarasi brocade silks with gold zari from Varanasi.",about:"Uttar Pradesh has two of India's most treasured crafts. Chikankari is a shadow-work embroidery in white on pale fabric—over 32 stitches creating floral motifs with luminous transparency. Banarasi silk sarees are woven with real gold and silver zari in intricate brocade patterns.",history:"Chikankari popularized by Nur Jahan, wife of Emperor Jahangir. Banarasi weaving has a documented 2,000-year history in Varanasi.",techniques:["32 Chikankari shadow stitches","White thread embroidery","Banarasi brocade weaving","Zari inlay","Jamdani design"],materials:"Muslin, georgette cotton, pure silk, real gold and silver zari, white thread",products:["Chikankari kurtas","Banarasi bridal sarees","Brocade fabric","Lehengas","Stoles"],recognition:"Lucknow Chikankari and Banaras Brocades Sarees both hold GI tags.",tags:["GI Tagged","Lucknow","Varanasi","Mughal Heritage","Embroidery","Silk Brocade","Bridal"]},
  INUT: { name:"Uttarakhand",craft:"Ringal Bamboo Craft & Aipan Art",desc:"Ringal (mountain bamboo) basketry from Kumaon hills, and Aipan—ritual white-red floor and wall patterns drawn for festivals and ceremonies.",about:"Uttarakhand's Ringal craft uses Himalayan bamboo to weave baskets and furniture. Aipan is a folk art tradition where women draw sacred white geometric patterns on red ochre backgrounds for religious ceremonies.",history:"Ringal weaving an ancient livelihood craft of mountain communities. Aipan rooted in Kumaoni folk culture, practiced for millennia during births, weddings, and festivals.",techniques:["Ringal splicing and weaving","Aipan rice-paste drawing","Geometric pattern drafting","Ochre preparation","Natural lacquering"],materials:"Ringal bamboo, natural lacquer, rice paste, red ochre earth, cotton cloth",products:["Ringal baskets","Aipan printed fabric","Mountain bamboo furniture","Woolen shawls","Folk paintings"],recognition:"Aipan recognized as important cultural tradition. Ringal craft supported by UCOST.",tags:["Himalayan","Mountain Craft","Folk Art","Ritual Art","Bamboo","Aipan","Kumaon"]},
  INWB: { name:"West Bengal",craft:"Muslin Weaving & Dokra Craft",desc:"The legendary Dhaka Muslin tradition—world's finest cotton—alongside Baluchari sarees, Kantha embroidery, and Bankura Dokra metal casting.",about:"West Bengal is home to the revival of Dhaka Muslin—so delicate it was called 'woven air' by Mughal emperors. The state also produces Baluchari sarees (woven Mughal scenes), Kantha embroidery (recycled thread storytelling), and Bankura Dokra metal craft.",history:"Muslin weaving in this delta region dates to antiquity. Baluchari sarees originated in Murshidabad under Nawab patronage in the 18th century.",techniques:["Fine cotton spinning","Jamdani weave","Baluchari supplementary weft","Kantha running stitch","Dokra lost-wax casting"],materials:"Phuti Karpas cotton, silk, metallic thread, recycled sari cloth (Kantha), brass alloy",products:["Muslin fabric","Baluchari sarees","Kantha quilts","Bankura horses","Dokra figurines"],recognition:"Baluchari Saree, Dhaniakhali Saree, and Gobindabhog hold GI tags. Kantha is internationally celebrated.",tags:["GI Tagged","Muslin","Baluchari","Kantha","Woven Air","Bengal Heritage","Saree"]}
};
const tooltip = document.getElementById('tooltip');
let activeEl = null;

function showTT(e, code) {
  const d = stateData[code]; if (!d) return;
  document.getElementById('tt-state').textContent = d.name;
  document.getElementById('tt-craft').textContent = d.craft;
  tooltip.classList.add('visible');
  moveTT(e);
}

function moveTT(e) {
  let x = e.clientX + 18, y = e.clientY - 14;
  if (x + 260 > window.innerWidth)  x = e.clientX - 270;
  if (y + 100 > window.innerHeight) y = e.clientY - 110;
  tooltip.style.left = x + 'px';
  tooltip.style.top  = y + 'px';
}

function hideTT() { tooltip.classList.remove('visible'); }
function updatePanel(code) {
  const d = stateData[code]; if (!d) return;
  document.getElementById('panel-idle').style.display = 'none';
  const pc = document.getElementById('panel-content');
  pc.classList.remove('show'); void pc.offsetWidth;
  document.getElementById('p-state').textContent = d.name;
  document.getElementById('p-craft').textContent = d.craft;
  document.getElementById('p-desc').textContent  = d.desc;
  document.getElementById('p-tags').innerHTML = d.tags.map(t => `<span class="p-tag">${t}</span>`).join('');
  const giWrap = document.getElementById('p-gi-wrap');
  if (d.recognition && d.recognition.includes('GI')) {
    giWrap.style.display = 'block';
    document.getElementById('p-gi-text').textContent = '✦ GI Tagged Craft';
  } else {
    giWrap.style.display = 'none';
  }
  pc.classList.add('show');
}
function openModal(code) {
  const d = stateData[code]; if (!d) return;
  document.getElementById('m-eyebrow').textContent   = 'India · Handicraft Heritage';
  document.getElementById('m-title').textContent     = d.craft;
  document.getElementById('m-subtitle').textContent  = d.name;
  document.getElementById('m-about').textContent     = d.about;
  document.getElementById('m-history').textContent   = d.history;
  document.getElementById('m-materials').textContent = d.materials;
  document.getElementById('m-techniques').innerHTML  = d.techniques.map(t => `<div class="feature-item">${t}</div>`).join('');
  document.getElementById('m-products').innerHTML    = d.products.map(p => `<div class="feature-item">${p}</div>`).join('');
  document.getElementById('m-recognition').textContent = d.recognition;
  document.getElementById('gi-block').style.display = d.recognition ? 'flex' : 'none';
  document.getElementById('m-keywords').innerHTML = d.tags.map(t => `<span class="keyword-pill">${t}</span>`).join('');
  document.getElementById('modal-overlay').classList.add('open');
  document.body.style.overflow = 'hidden';
}

function closeModal() {
  document.getElementById('modal-overlay').classList.remove('open');
  document.body.style.overflow = '';
}

function closeModalOutside(e) {
  if (e.target === document.getElementById('modal-overlay')) closeModal();
}

document.addEventListener('keydown', e => { if (e.key === 'Escape') closeModal(); });
window.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('[class*="sm_state_"]').forEach(el => {
    const cls = el.getAttribute('class') || '';
    const m = cls.match(/sm_state_([A-Z0-9]+)/);
    if (!m) return;
    const code = m[1];
    el.addEventListener('mouseenter', e => {
      showTT(e, code);
      updatePanel(code);
      if (activeEl) activeEl.classList.remove('active');
      el.classList.add('active');
      activeEl = el;
    });
    el.addEventListener('mousemove', moveTT);
    el.addEventListener('mouseleave', hideTT);
    el.addEventListener('click', () => openModal(code));
  });
});